/**
 * CV storage migrator
 * ============================================================================
 *
 * Versioning policy
 * -----------------
 *   v1  = no `version` key in the stored payload (legacy shape, all data
 *         written before Task 1 landed)
 *   v2  = this commit's output (Task 1)
 *   v3  = will be added when Task 5 lands; do NOT edit this file at that
 *         point — write a new `migrateV2ToV3` step. Each version's
 *         transform function is committed once and never edited again.
 *
 * What v1 → v2 does (this file)
 * -----------------------------
 *   1. `languages[].level` enum is tightened from 8 historical values to
 *      the 4 values used going forward (Native / Fluent / Professional /
 *      Conversational). Existing values are mapped per the spec; any
 *      value we don't recognise falls back to 'conversational' with a
 *      console.warn (no PII logged).
 *   2. Empty defaults are populated for genuinely new v2 fields:
 *        personal.fullNameArabic = ""
 *        personal.emiratesIdYear = ""
 *        personal.openTo         = []
 *        boardRoles              = []
 *        awards                  = []
 *      Enum-typed new fields (visaStatus, emiratesId, noticePeriod) and
 *      nested objects (scopeBand, experience[].scopeMetrics) stay
 *      omitted — empty string would violate the enum, and the gated
 *      objects only exist when the user opts in.
 *   3. `version: 2` is stamped LAST. If any transform throws, the catch
 *      path returns the original payload unchanged so the user never
 *      ends up with data marked as v2 in v1 shape.
 *
 * Deferred to v2 → v3 (Task 5)
 * -----------------------------
 *   The original Task 1 spec also called for two shape collapses. They
 *   are intentionally NOT in this commit, because every reader-side
 *   consumer below currently reads the v1 shape. Running these
 *   transforms in isolation would silently break rendering for every
 *   existing user on next page load.
 *
 *     A. Collapse `experience[].isCurrent` + `experience[].endDate`
 *        into `experience[].endDate: string | 'present'`.
 *        Consumers that read `isCurrent` today (must update in Task 5):
 *          - lib/utils/format.ts                  (formatDateRange)
 *          - lib/templates/classic.tsx
 *          - lib/templates/modern.tsx
 *          - lib/templates/executive.tsx
 *          - lib/templates/ats-clean.tsx
 *          - lib/templates/exec-split.tsx
 *          - lib/templates/corp-sidebar.tsx
 *          - components/pdf/CVDocument.tsx
 *          - lib/utils/docxExport.ts
 *          - lib/scoreEngine.ts
 *          - lib/importers/* (parser fallback)
 *          - components/builder/steps/ExperienceStep.tsx
 *
 *     B. Rename `certifications[].date` → `certifications[].year`.
 *        Consumers that read `cert.date` today (must update in Task 5):
 *          - All 6 templates listed above
 *          - components/pdf/CVDocument.tsx
 *          - lib/utils/docxExport.ts
 *
 *   Re-grep for both `isCurrent` and `\.date\b` before relying on this
 *   list — it was exhaustive at the time of writing this file but the
 *   codebase will move.
 *
 * Task 5 instructions
 * -------------------
 *   1. Append a `migrateV2ToV3(payload)` function in this file.
 *      Do NOT edit `migrateV1ToV2` — its output is the contract that
 *      v2-stamped data in the wild conforms to.
 *   2. In v2 → v3:
 *        - For each experience: if `isCurrent === true` set
 *          `endDate = 'present'`, then delete `isCurrent`.
 *        - For each certification: parse a 4-digit year from `date`;
 *          if found, write to `year` and delete `date`. If no year can
 *          be parsed, KEEP `date` as-is and do NOT write `year` —
 *          preserve user data, never silently destroy it.
 *   3. Update every consumer in the lists above to read the new shape.
 *      Land migrator + readers in the same commit.
 *   4. Bump CURRENT_VERSION to 3 and add the v2 → v3 dispatch in
 *      `migrate()` below the existing v1 → v2 branch.
 *
 * ============================================================================
 */

import type { CvData } from "../types/cv";

export const CURRENT_VERSION = 2 as const;

// ── Language level mapping ──────────────────────────────────────────────────

const V1_LANGUAGE_LEVELS = [
  "elementary",
  "conversational",
  "professional",
  "full_professional",
  "native",
  "beginner",
  "intermediate",
  "advanced",
] as const;
type V1LanguageLevel = (typeof V1_LANGUAGE_LEVELS)[number];

const V2_LANGUAGE_LEVELS = [
  "native",
  "fluent",
  "professional",
  "conversational",
] as const;
export type V2LanguageLevel = (typeof V2_LANGUAGE_LEVELS)[number];

const LANGUAGE_LEVEL_MAP: Record<V1LanguageLevel, V2LanguageLevel> = {
  elementary: "conversational",
  conversational: "conversational",
  professional: "professional",
  full_professional: "professional",
  native: "native",
  beginner: "conversational",
  intermediate: "professional",
  advanced: "fluent",
};

const UNMAPPED_LANGUAGE_FALLBACK: V2LanguageLevel = "conversational";

const isV2LanguageLevel = (v: string): v is V2LanguageLevel =>
  (V2_LANGUAGE_LEVELS as readonly string[]).includes(v);

const isV1LanguageLevel = (v: string): v is V1LanguageLevel =>
  (V1_LANGUAGE_LEVELS as readonly string[]).includes(v);

export function migrateLanguageLevel(raw: unknown): V2LanguageLevel | undefined {
  if (raw === undefined || raw === null || raw === "") return undefined;
  if (typeof raw !== "string") {
    console.warn(
      `[makemycv] migrate: language level was non-string → defaulting to '${UNMAPPED_LANGUAGE_FALLBACK}'`
    );
    return UNMAPPED_LANGUAGE_FALLBACK;
  }
  const normalised = raw.toLowerCase();
  if (isV1LanguageLevel(normalised)) return LANGUAGE_LEVEL_MAP[normalised];
  if (isV2LanguageLevel(normalised)) return normalised;
  console.warn(
    `[makemycv] migrate: unmapped language level → defaulting to '${UNMAPPED_LANGUAGE_FALLBACK}'`
  );
  return UNMAPPED_LANGUAGE_FALLBACK;
}

// ── Helpers ─────────────────────────────────────────────────────────────────

type AnyObject = Record<string, unknown>;

const isPlainObject = (v: unknown): v is AnyObject =>
  typeof v === "object" && v !== null && !Array.isArray(v);

// ── v1 → v2 ─────────────────────────────────────────────────────────────────

function migrateV1ToV2(payload: AnyObject): AnyObject {
  // Shallow clone — never mutate the caller's input
  const out: AnyObject = { ...payload };

  // Personal: empty defaults for genuinely new v2 fields
  const personalSrc = isPlainObject(out.personal) ? out.personal : {};
  const personal: AnyObject = { ...personalSrc };
  if (personal.fullNameArabic === undefined) personal.fullNameArabic = "";
  if (personal.emiratesIdYear === undefined) personal.emiratesIdYear = "";
  if (!Array.isArray(personal.openTo)) personal.openTo = [];
  // visaStatus / emiratesId / noticePeriod stay omitted (enum-typed)
  out.personal = personal;

  // Languages: tighten level enum to 4 values
  if (Array.isArray(out.languages)) {
    out.languages = out.languages.map((entry) => {
      if (!isPlainObject(entry)) return entry;
      const next: AnyObject = { ...entry };
      if (next.level !== undefined) {
        const migrated = migrateLanguageLevel(next.level);
        if (migrated === undefined) {
          delete next.level;
        } else {
          next.level = migrated;
        }
      }
      return next;
    });
  }

  // Top-level new repeaters
  if (!Array.isArray(out.boardRoles)) out.boardRoles = [];
  if (!Array.isArray(out.awards)) out.awards = [];
  // scopeBand stays omitted (T3-only opt-in)

  // Version stamp — LAST. Anything above that throws bypasses this line,
  // and the catch path in `migrate()` returns the original payload.
  out.version = 2;
  return out;
}

// ── Public entry point ──────────────────────────────────────────────────────

export type MigrationOutcome =
  | { status: "migrated"; from: 1; to: 2 }
  | { status: "skipped"; version: number }
  | { status: "fresh" }
  | { status: "failed"; reason: string };

export type MigrationResult = {
  data: CvData | null;
  outcome: MigrationOutcome;
};

export function migrate(parsed: unknown): MigrationResult {
  if (parsed === null || parsed === undefined) {
    return { data: null, outcome: { status: "fresh" } };
  }
  if (!isPlainObject(parsed)) {
    return { data: null, outcome: { status: "failed", reason: "not-an-object" } };
  }

  const versionRaw = parsed.version;
  const version =
    typeof versionRaw === "number" && Number.isFinite(versionRaw) ? versionRaw : 1;

  // Already current, or ahead of us (e.g. user opened an older app build
  // after using a newer one) → return as-is, do nothing.
  if (version >= CURRENT_VERSION) {
    return {
      data: parsed as unknown as CvData,
      outcome: { status: "skipped", version },
    };
  }

  try {
    const migrated = migrateV1ToV2(parsed);
    return {
      data: migrated as unknown as CvData,
      outcome: { status: "migrated", from: 1, to: 2 },
    };
  } catch (err) {
    const reason = err instanceof Error ? err.message : "unknown";
    // Hand back the ORIGINAL payload (never partially-migrated) so the
    // caller can keep rendering v1 data; the catch path is the integrity
    // guarantee against half-applied migrations.
    return {
      data: parsed as unknown as CvData,
      outcome: { status: "failed", reason },
    };
  }
}
